site_name: Linkerd Docs

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Linkerd-18 - Linkerd Case Study: "index.md"
  - Background: "background.md"
  - Case study concept: "case_study_concept"
  - Environment configuration description: "environment_configuration_description.md"
  - Solution architecture: "solution_architecture.md"
  - Demo and step by step instruction:
      - "Consfiguration set-up": "test.md"
      - "Execution procedure": "test.md"
      - "Plaintext sniffing": "test.md"
      - "Ciphertext sniffing": "test.md"
  - Team and contribution: "team_and_contribution.md"

plugins:
  - search
  - bibtex:
      bib_file: "docs/refs.bib"

markdown_extensions:
  - footnotes
